apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-monitor-stdout
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-monitor-stdout
  template:
    metadata:
      labels:
        app: deis-monitor-stdout
    spec:
      containers:
      - name: deis-monitor-stdout
        image: quay.io/deis/stdout-metrics:canary
        imagePullPolicy: Always
        ports:
        - containerPort: 1514
          name: transport
          protocol: UDP
