apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-stdout
  namespace: deis
  labels:
    heritage: deis
    app: deis-monitor-stdout
spec:
  ports:
  - port: 514
    name: transport
    targetPort: 1514
    protocol: UDP
  selector:
    app: deis-monitor-stdout
