apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-monitor-nginxpusher
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-monitor-nginxpusher
  template:
    metadata:
      labels:
        app: deis-monitor-nginxpusher
    spec:
      containers:
      - name: deis-monitor-nginxpusher
        image: quay.io/deis/nginxpusher:canary
        imagePullPolicy: Always
        ports:
        - containerPort: 1514
          name: transport
          protocol: UDP
